import type { NextPage } from 'next'
import Head from 'next/head'

const Component: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full flex justify-center items-center">
        <h1 className="text-5xl text-center">
          Component Wow!!
        </h1>
      </main>
    </>
  )
}

export default Component
